### PR TITLE
Doc improvements

### PR DESCRIPTION
**Pull request by Ra2-IFV**
Leave a comment if you disagree with some changes and I'll work on it.

### CODE REVIEW

**Comment by Simple-Tracker** [comment]
Good work.

The only problem is that independent file configuration files means that they need to maintain two changes at the same time, including the default value.However, considering the documentation and the detailed list of keys when loading the configuration file, I wonder if this is necessary.

**Comment by Ra2-IFV** [comment]
Value types. Not everyone knows json well, they may accidentally add double quotes to a `int` type value and then program explodes (just my bs imagings)
If you want to eliminate this file, I suggest to replace original `config.json` with this full `config.json`, or let program extend from empty/partial configs.

**Comment by Simple-Tracker** [comment]
Reasonable, I guess we can use a single complete configuration file, but use comments.

**Comment by Ra2-IFV** [comment]
Agree, comment most key value pairs and leaves necessary things.  
So I should follow the current `config.json`?

**Comment by IAALAI** [comment]
> Value types. Not everyone knows json well, they may accidentally add double quotes to a type value and then program explodes (just my bs imagings) If you want to eliminate this file, I suggest to replace original with this full , or let program extend from empty/partial configs.`int``config.json``config.json`

会少双引号？是不是应该换一个好一点的编辑器？

**Comment by Ra2-IFV** [comment]
> 会少双引号？是不是应该换一个好一点的编辑器？

As I said not everyone use vscode and know json syntax if you want to make this project more user-friendly then you should make most things work out-of-box, and it costs nothing, why not make it easier to use?
Also you may misunderstand something, I mean, **ADD** double quotes to a `int` type value

**Comment by Simple-Tracker** [comment]
The relevant PR has been merged and the conflict has been resolved!

I hope to change it to a single file comment method, so that there is no need to modify README.md and maintain a complete JSON file.

Additionally, the values ​​inside should be consistent with the default values, for example the value of clientUsername should be an empty string (but it does have quotes so it doesn't cause confusion)

**Comment by Ra2-IFV** [comment]
> Additionally, the values ​​inside should be consistent with the default values, for example the value of clientUsername should be an empty string

That's a mistake, shouldn't happen! I have same idea with you but I accidentally applied my own configuration on it...
Now I have to change my qbittorrent password :(

**Comment by Ra2-IFV** [comment]
I didn't even use a new branch to commit my changes. Stupid.  

https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/blob/726db1aa71f0476ab46e2afa11915f3703762f65/config.json#L21
https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/blob/726db1aa71f0476ab46e2afa11915f3703762f65/config.json#L25  
Should we merge it? `Gopeed` will match both `Gopeed` and `Gopeed dev` if using regular expression I guess

**Comment by Simple-Tracker** [comment]
Just use the current config.json. I'm not sure if anyone uses the non-dev version, and the ban is mainly based on IP.

**Comment by Ra2-IFV** [comment]
Rebased, formated and merged.

**Pull request merged**
